# Configuration for OpenVeth Managed Switch (SNMP)

# Listen for connections on all interfaces (port 161)
agentAddress  udp:161

# Community string "public" for Read-Only access from any source (for lab purposes)
rocommunity public default

# System Information
sysLocation    "OpenVeth Lab"
sysContact     "admin@openveth.local"
sysServices    72

